name: .NET

on:
  push:
    branches: [ master, develop, feature/*, hotfix/*, release/* ]
  pull_request:
    branches: [ master, develop, feature/*, hotfix/*, release/* ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with: 
        fetch-depth: '0'
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --logger "trx;LogFileName=test-results.trx" --no-build --verbosity normal
    - name: Upload Test Results
      uses: actions/upload-artifact@v2  # upload test results
      if: success() || failure()      # run this step even if previous step failed
      with:
          name: test-results
          path: 'tests/**/*.trx'

