name: .NET

on:
  push:
    branches: [ master, develop, feature/*, hotfix/*, release/* ]
  pull_request:
    branches: [ master, develop, feature/*, hotfix/*, release/*, !dependabot/* ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with: 
        fetch-depth: '0'
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --logger "trx;LogFileName=test-results.trx" --no-build --verbosity normal
    - name: Test Reporter
      uses: dorny/test-reporter@v1.4.2
      if: success() || failure()
      with: 
        name: Tests
        path: 'tests/**/*.trx'
        reporter: dotnet-trx
        fail-on-error: true

