name: 'Test Reporter'

on:
  workflow_run:
    workflows: ['.Net'] # runs after .Net workflow
    types:
      - completed

jobs:
  report:

    runs-on: ubuntu-latest

    steps:
    - name: Test Reporter
      uses: dorny/test-reporter@v1.4.2
      with: 
        artifact: test-results
        name: Tests
        path: '**/*.trx'
        reporter: dotnet-trx
        fail-on-error: true

